name: Generate Schemas
on: [workflow_dispatch]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean compile
      - run: |
          java -jar target/dphe-to-json-1.0-SNAPSHOT.jar \
          https://github.com/DeepPhe/dphe-neo4j.git master \
          src/main/java/org/healthnlp/deepphe/neo4j/node/xn ./schemas
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update schemas
