name: Generate Schemas
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build shaded jar
        run: mvn -B -DskipTests package
      - run: |
          java -jar target/dphe-to-json-1.0-SNAPSHOT.jar \
          https://github.com/DeepPhe/dphe-neo4j.git master \
          src/main/java/org/healthnlp/deepphe/neo4j/node/xn ./schemas/v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update schemas
      - name: Create pull request with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-schemas-v1
          title: "chore(schemas): update generated schemas in schemas/v1"
          commit-message: "chore(schemas): update generated JSON Schemas (schemas/v0.7.0)"
          add-paths: |
            schemas/v0.7.0/**
          body: |
            Automated refresh of generated JSON Schemas in `schemas/v0.7.0/`.
            Source: `${{ github.repository }}@${{ github.sha }}`.
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
