name: Generate Schemas

on: [push]

env:
  SCHEMA_VERSION: "0.7.0"  # change once, used everywhere

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build shaded jar
        run: mvn -B -DskipTests package

      - name: Generate schemas
        run: |
          mkdir -p "schemas/v${SCHEMA_VERSION}"
          java -jar target/dphe-to-json-1.0-SNAPSHOT.jar \
            https://github.com/DeepPhe/dphe-neo4j.git master \
            src/main/java/org/healthnlp/deepphe/neo4j/node/xn \
            "schemas/v${SCHEMA_VERSION}"

      - name: Create pull request with changes
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-schemas-v${{ env.SCHEMA_VERSION }}
          base: main                      # set your default branch if not 'main'
          title: "chore(schemas): update generated schemas in schemas/v${{ env.SCHEMA_VERSION }}"
          commit-message: "chore(schemas): update generated JSON Schemas (schemas/v${{ env.SCHEMA_VERSION }})"
          add-paths: |
            schemas/v${{ env.SCHEMA_VERSION }}/**
          body: |
            Automated refresh of generated JSON Schemas in `schemas/v${{ env.SCHEMA_VERSION }}/`.
            Source: `${{ github.repository }}@${{ github.sha }}`.
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          labels: |
            automated
            schemas

      - name: PR link
        if: ${{ steps.cpr.outputs.pull-request-url }}
        run: |
          echo "Created PR: ${{ steps.cpr.outputs.pull-request-url }}"

